apiVersion: v1
kind: ConfigMap
metadata:
  name: arvados-api-server-configmap
  labels:
    app: arvados-api-server
    chart: {{ template "arvados.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ (.Files.Glob "config/api-server/*").AsConfig | indent 2 }}
