apiVersion: v1
kind: ConfigMap
metadata:
  name: arvados-keep-store-configmap
  labels:
    app: {{ template "arvados.name" . }}
    chart: {{ template "arvados.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  blob-signing.key: key
