apiVersion: v1
kind: ConfigMap
metadata:
  name: arvados-shell-server-configmap
  labels:
    app: {{ template "arvados.name" . }}
    chart: {{ template "arvados.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ (.Files.Glob "config/shell-server/*").AsConfig | indent 2 }}
