apiVersion: v1
kind: Service
metadata:
  name: arvados-workbench
  labels:
    app: {{ template "arvados.name" . }}
    chart: {{ template "arvados.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: LoadBalancer
  loadBalancerIP: "8.8.8.8"
  ports:
  - name: http
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: arvados-workbench
