apiVersion: v1
kind: ConfigMap
metadata:
  name: arvados-workbench-configmap
  labels:
    app: {{ template "arvados.name" . }}
    chart: {{ template "arvados.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ (.Files.Glob "config/workbench/*").AsConfig | indent 2 }}
