apiVersion: v1
kind: Service
metadata:
  name: arvados-ws
  labels:
    app: {{ template "arvados.name" . }}
    chart: {{ template "arvados.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - name: http
    port: 9003
    targetPort: 9003
    protocol: TCP
  selector:
    app: arvados-ws
